### ISSUE TITLE
[ERROR] Not yet supported by the V8 runtime

### ISSUE THREAD

**Issue by ximerus** [chaitin/passionfruit#51]
Hi. Today I'm installed passionfruit and tried to use it, and when I'm tried to inspect some app I got an error **not yet supported by the V8 runtime**.  Near is log text:

>   <-- GET /
>   --> GET / 200 8ms 338b
>   <-- GET /static/build.js
>   <-- GET /static/0.build.js
>   <-- GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe
>   <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
>   --> GET /static/0.build.js 200 5ms 55.2kb
>   --> GET /static/MaterialIcons-Regular.woff2?570eb83859dc23dd0eec423a49e147fe 200 6ms 43.26kb
>   --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 6ms 16.33kb
>   --> GET /static/build.js 200 28ms 865.29kb
>   <-- GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1
>   --> GET /static/logo.svg?abda96cf81a18b28052a52d16b35d4e1 200 5ms 16.33kb
> An unhandledRejection occurred:
> Rejection: Error: GDBus.Error:re.frida.Error.InvalidArgument: not yet supported by the V8 runtime
> Error: GDBus.Error:re.frida.Error.InvalidArgument: not yet supported by the V8 runtime

Can anybody explain to me what's wrong with it, and how to fix?

**Comment by levicn** [comment]
same problem

**Comment by ChiChou** [comment]
I've recently upgrade the server side to latest `frida`. Can you show me the version of your frida on iOS device?

**Comment by ximerus** [comment]
Here is the version on my iPhone:
`~ root# frida-server --version`
`12.6.7`

And here is the version on my MacBook:
`frida --version`
`12.6.7`

**Comment by OverflowMyBuffers** [comment]
Same problem here, running this version of frida:

`root# frida-server --version
12.6.8
`

Error with passionfruit:
`Rejection: Error: GDBus.Error:re.frida.Error.InvalidArgument: not yet supported by the V8 runtime`

**Comment by ChiChou** [comment]
Sorry, forgot to update package.json.
Should be fixed now

**Comment by pandasauce** [comment]
Still not working on 0.5.1. Same error, `frida-server` 12.6.8.

**Comment by hduarte** [comment]
Same Issue here

**Comment by 0roman** [comment]
Same Issue here.

**Comment by shuax** [comment]
same error

**Comment by pich4ya** [comment]
I was able to resolve this issue by building it from current master branch.

```$ git clone https://github.com/chaitin/passionfruit.git
$ npm install
$ npm run dev```

**Comment by chisana-mori** [comment]
Same issue here,all packages are latest version.

**Comment by chisana-mori** [comment]
> npm run dev

thanks,it worked for me.

**Comment by ShilpaRanganatha** [comment]
I am getting the same issue - "Rejection: Error: GDBus.Error:re.frida.Error.InvalidArgument: not yet supported by the V8 runtime"

**Comment by ChiChou** [comment]
Sorry. The root cause is that from v0.5.1 I have moved to v8 engine, which doesn't support bytecode. It should be gone after v0.5.3.
